version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger
  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - "./otel-collector.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    networks:
      - jaeger
    depends_on:
      - jaeger

networks:
  jaeger:
